---
kind: Service
apiVersion: v1
metadata:
  name: unbound-udp
  namespace: infrastructure
  annotations:
    metallb.universe.tf/allow-shared-ip: unbound
spec:
  selector:
    app: unbound
  ports:
  - protocol: UDP
    port: 53
    name: dnsudp
    targetPort: 53
  type: LoadBalancer
  loadBalancerIP: 192.168.8.1
---
kind: Service
apiVersion: v1
metadata:
  name: unbound-tcp
  namespace: infrastructure
  annotations:
    metallb.universe.tf/allow-shared-ip: unbound
spec:
  selector:
    app: unbound
  ports:
  - protocol: TCP
    port: 53
    name: dnstcp
    targetPort: 53
  type: LoadBalancer
  loadBalancerIP: 192.168.8.1
