---
apiVersion: v1
kind: Service
metadata:
  namespace: storage
  name: greyhole-database
spec:
  ports:
    - port: 3306
  selector:
    role: greyhole-database
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: storage
  name: greyhole-database
  labels:
    app: greyhole
spec:
  replicas: 1
  selector:
    matchLabels:
      role: greyhole-database
  template:
    metadata:
      labels:
        role: greyhole-database
    spec:
      containers:
      - name: mysql
        image: dragoncrafted87/greyhole-database:edge
        imagePullPolicy: Always
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: greyhole-database-pass
              key: password
        - name: MYSQL_DATABASE
          value: greyhole
        - name: MYSQL_USER
          value: greyhole_user
        - name: MYSQL_PASSWORD
          value: '89y63jdwe'
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: greyhole-database
          mountPath: /var/lib/mysql
      volumes:
      - name: greyhole-database
        nfs:
          server: 10.152.183.171
          path: /greyhole/database
