apiVersion: v1
kind: Service
metadata:
  namespace: media
  name: jellyfin-tcp
  annotations:
    metallb.universe.tf/allow-shared-ip: jellyfin
spec:
  ports:
  - name: web
    port: 80
    targetPort: 8096
    protocol: TCP
  selector:
    role: jellyfin
  type: LoadBalancer
  loadBalancerIP: 192.168.8.30
