apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: media
  name: jellyfin
  labels:
    app: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      role: jellyfin
  template:
    metadata:
      labels:
        role: jellyfin
    spec:
      nodeSelector:
        kubernetes.io/hostname: amd64node4.lan
      containers:
      - name: jellyfin
        image: jellyfin/jellyfin:10.8.4-1
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: America/Chicago
        livenessProbe:
          tcpSocket:
            port: 8096
          initialDelaySeconds: 60
          periodSeconds: 5
        ports:
        - name: server
          containerPort: 8096
          protocol: TCP
        volumeMounts:
        - name: media
          mountPath: /data/media
        - name: configuration
          mountPath: /config
      volumes:
      - name: media
        flexVolume:
          driver: fstab/cifs
          secretRef:
            name: cifs-secret
          options:
            networkPath: //192.168.8.2/Storage/Media/
            mountOptions: dir_mode=0755,file_mode=0644,noperm
      - name: configuration
        nfs:
          server: 192.168.0.200
          path: /srv/data/jellyfin-config/
