---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: pi-hole
  name: pihole
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "500Mi"
