---
apiVersion: v1
kind: Service
metadata:
  namespace: pi-hole
  name: pi-hole
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole
spec:
  ports:
    - name: dns
      port: 53
      protocol: TCP
    - name: http
      port: 80
      protocol: TCP
    - name: https
      port: 443
      protocol: TCP
  selector:
    role: pi-hole
  type: LoadBalancer
  loadBalancerIP: 192.168.8.1
---
apiVersion: v1
kind: Service
metadata:
  namespace: pi-hole
  name: pi-hole-udp
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole
spec:
  ports:
    - name: dns-udp
      nodePort: 32456
      port: 53
      protocol: UDP
      targetPort: dns-udp
    - name: client-udp
      nodePort: 31678
      port: 67
      protocol: UDP
      targetPort: client-udp
  selector:
    role: pi-hole
  type: LoadBalancer
  loadBalancerIP: 192.168.8.1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: pi-hole
  name: pi-hole
  labels:
    app: pi-hole
spec:
  replicas: 1
  selector:
    matchLabels:
      role: pi-hole
  template:
    metadata:
      labels:
        role: pi-hole
    spec:
      containers:
      - name: pihole
        image: pihole/pihole:latest
        imagePullPolicy: Always
        env:
        - name: WEB_PORT
          value: "80"
        - name: WEBPASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: pihole-secret
        - name: TZ
          value: America/Chicago
        - name: DNS1
          value: 1.1.1.1
        - name: DNS2
          value: 1.0.0.1
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 53
          name: dns
          protocol: TCP
        - containerPort: 53
          name: dns-udp
          protocol: UDP
        - containerPort: 443
          name: https
          protocol: TCP
        - containerPort: 67
          name: client-udp
          protocol: UDP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /admin.index.php
            port: http
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /admin.index.php
            port: http
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        volumeMounts:
        - name: config
          mountPath: "/etc/pihole"
        - name: dnsmasq
          mountPath: "/etc/dnsmasq.d"
      volumes:
      - name: config
        nfs:
          server: 10.98.210.174
          path: /Pi-Hole/config

      - name: dnsmasq
        nfs:
          server: 10.98.210.174
          path: /Pi-Hole/dnsmasq
