apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: games
  name: minecraft-vpp
  labels:
    app: minecraft-vpp
spec:
  replicas: 1
  selector:
    matchLabels:
      role: minecraft-vpp
  template:
    metadata:
      labels:
        role: minecraft-vpp
    spec:
      nodeSelector:
        kubernetes.io/hostname: amd64node5.lan
      securityContext:
        fsGroup: 1000
      containers:
      - name: minecraft-vpp
        image: dragoncrafted87/alpine-minecraft:edge
        imagePullPolicy: Always
        env:
        - name: TZ
          value: America/Chicago
        - name: MINECRAFT_VERSION
          value: '1.19'
        ports:
        - name: minecraft
          containerPort: 25565
          protocol: TCP
        - name: rcon
          containerPort: 25575
          protocol: TCP
        - name: voice
          containerPort: 24454
          protocol: UDP
        - name: bedrock
          containerPort: 19132
          protocol: UDP
        volumeMounts:
        - name: vanillaplusplus
          mountPath: /mnt/minecraft
        - name: local-volume
          mountPath: /mnt/ramdisk
        - name: ram-volume
          mountPath: /mnt/ramdisk/world
        - name: config
          mountPath: /mnt/ramdisk/modlist.conf
          subPath: modlist.conf
          readOnly: true
      volumes:
      - name: vanillaplusplus
        nfs:
          server: 10.152.183.213
          path: /minecraft-vanillaplusplus
      - name: local-volume
        emptyDir: {}
      - name: ram-volume
        emptyDir:
          medium: Memory
      - name: config
        configMap:
          name: mc-vpp-config
          items:
          - key: modlist
            path: modlist.conf
