---
apiVersion: v1
kind: Service
metadata:
    namespace: games
    name: minecraft
    annotations:
        metallb.universe.tf/allow-shared-ip: minecraft
spec:
    ports:
    -   name: minecraft
        port: 25565
        protocol: TCP
    -   name: rcon
        port: 25575
        protocol: TCP
    selector:
        role: minecraft
    type: LoadBalancer
    loadBalancerIP: 192.168.8.3
---
apiVersion: v1
kind: Service
metadata:
    namespace: games
    name: minecraft-udp
    annotations:
        metallb.universe.tf/allow-shared-ip: minecraft
spec:
    ports:
    -   name: voice
        port: 24454
        protocol: UDP
    selector:
        role: minecraft
    type: LoadBalancer
    loadBalancerIP: 192.168.8.3
