apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: games
  name: minecraft
  labels:
    app: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      role: minecraft
  template:
    metadata:
      labels:
        role: minecraft
    spec:
      nodeSelector:
        kubernetes.io/hostname: "amd64node3.lan"
      containers:
      - name: minecraft
        image: dragoncrafted87/alpine-minecraft:edge
        imagePullPolicy: Always
        ports:
        - name: minecraft
          containerPort: 25565
          protocol: TCP
        - name: rcon
          containerPort: 25575
          protocol: TCP
        volumeMounts:
        - name: vanillaplusplus
          mountPath: /mnt/minecraft
        - name: local-volume
          mountPath: /mnt/ramdisk
        - name: ram-volume
          mountPath: /mnt/ramdisk/world
      volumes:
      - name: vanillaplusplus
        nfs:
          server: 10.152.183.171
          path: /minecraft-vanillaplusplus
      - name: local-volume
        emptyDir: {}
      - name: ram-volume
        emptyDir:
          medium: Memory
