apiVersion: batch/v1
kind: CronJob
metadata:
  name: mc-vpp-backup-job
  namespace: storage
  labels:
    app: mc-vpp-backup-job
spec:
  schedule: 0 2 * * *
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          name: mc-vpp-backup-job
        spec:
          containers:
          - name: mc-vpp-backup
            image: ghcr.io/dragoncrafted87/alpine-backup-cron:2.0.1
            imagePullPolicy: IfNotPresent
            env:
            - name: TZ
              value: America/Chicago
            - name: BACKUP_NAME
              value: minecraft-vpp-backup
            volumeMounts:
            - name: minecraft
              mountPath: /mnt/source
            - name: backup
              mountPath: /mnt/backups
          restartPolicy: OnFailure
          volumes:
          - name: minecraft
            nfs:
              server: 192.168.0.1
              path: /srv/data/minecraft-vanillaplusplus
          - name: backup
            flexVolume:
              driver: fstab/cifs
              secretRef:
                name: cifs-secret
              options:
                networkPath: //192.168.8.2/Backups/K8s/
                mountOptions: dir_mode=0755,file_mode=0644,noperm
