---
apiVersion: v1
kind: Service
metadata:
  namespace: games
  name: minecraft-uhc
  annotations:
    metallb.universe.tf/allow-shared-ip: minecraft-uhc
spec:
  ports:
  - name: minecraft
    port: 25565
    protocol: TCP
  - name: rcon
    port: 25575
    protocol: TCP
  selector:
    role: minecraft-uhc
  type: LoadBalancer
  loadBalancerIP: 192.168.8.4
---
apiVersion: v1
kind: Service
metadata:
  namespace: games
  name: minecraft-uhc-udp
  annotations:
    metallb.universe.tf/allow-shared-ip: minecraft-uhc
spec:
  ports:
  - name: voice
    port: 24454
    protocol: UDP
  selector:
    role: minecraft-uhc
  type: LoadBalancer
  loadBalancerIP: 192.168.8.4
