apiVersion: apps/v1
kind: Deployment
metadata:
    namespace: games
    name: minecraft-uhc
    labels:
        app: minecraft-uhc
spec:
    replicas: 1
    selector:
        matchLabels:
            role: minecraft-uhc
    template:
        metadata:
            labels:
                role: minecraft-uhc
        spec:
            nodeSelector:
                kubernetes.io/hostname: amd64node5.lan
            containers:
            -   name: minecraft-uhc
                image: dragoncrafted87/alpine-minecraft:edge
                imagePullPolicy: Always
                env:
                -   name: TZ
                    value: America/Chicago
                -   name: MINECRAFT_VERSION
                    value: 1.18.2
                ports:
                -   name: minecraft
                    containerPort: 25565
                    protocol: TCP
                -   name: rcon
                    containerPort: 25575
                    protocol: TCP
                -   name: voice
                    containerPort: 24454
                    protocol: UDP
                volumeMounts:
                -   name: minecraft-data
                    mountPath: /mnt/minecraft
                -   name: local-volume
                    mountPath: /mnt/ramdisk
                -   name: ram-volume
                    mountPath: /mnt/ramdisk/world
                -   name: config
                    mountPath: /mnt/ramdisk/modlist.conf
                    subPath: modlist.conf
                    readOnly: true
            volumes:
            -   name: minecraft-data
                nfs:
                    server: 10.152.183.213
                    path: /minecraft-hardcore
            -   name: local-volume
                emptyDir: {}
            -   name: ram-volume
                emptyDir:
                    medium: Memory
            -   name: config
                configMap:
                    name: mc-uhc-config
                    items:
                    -   key: modlist
                        path: modlist.conf
