apiVersion: batch/v1
kind: CronJob
metadata:
  name: kitchenowl-backup-job
  namespace: storage
  labels:
    app: kitchenowl-backup-job
spec:
  schedule: 10 4 * * *
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          name: kitchenowl-backup-job
        spec:
          containers:
          - name: kitchenowl-backup
            image: ghcr.io/dragoncrafted87/alpine-backup-cron:2.0.1
            imagePullPolicy: IfNotPresent
            env:
            - name: TZ
              value: America/Chicago
            - name: BACKUP_NAME
              value: kitchenowl
            volumeMounts:
            - name: kitchenowl
              mountPath: /mnt/source
            - name: backup
              mountPath: /mnt/backups
          restartPolicy: OnFailure
          volumes:
          - name: kitchenowl
            nfs:
              server: hoard-drake.stealthdragonland.net
              path: /srv/data/kitchenowl
          - name: backup
            persistentVolumeClaim:
              claimName: calligraphy-backups
