apiVersion: v1
kind: Service
metadata:
  namespace: media
  name: prayers-tcp
  annotations:
    metallb.universe.tf/allow-shared-ip: prayers
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
  selector:
    role: prayers
  type: LoadBalancer
  loadBalancerIP: 192.168.8.31
