---
apiVersion: v1
kind: Service
metadata:
    namespace: dns
    name: pi-hole
    annotations:
        metallb.universe.tf/allow-shared-ip: pihole
spec:
    ports:
    -   name: dns
        port: 53
        protocol: TCP
    -   name: http
        port: 80
        protocol: TCP
    -   name: https
        port: 443
        protocol: TCP
    selector:
        role: pi-hole
    type: LoadBalancer
    loadBalancerIP: 192.168.8.1
---
apiVersion: v1
kind: Service
metadata:
    namespace: dns
    name: pi-hole-udp
    annotations:
        metallb.universe.tf/allow-shared-ip: pihole
spec:
    ports:
    -   name: dns-udp
        nodePort: 32456
        port: 53
        protocol: UDP
        targetPort: dns-udp
    -   name: client-udp
        nodePort: 31678
        port: 67
        protocol: UDP
        targetPort: client-udp
    selector:
        role: pi-hole
    type: LoadBalancer
    loadBalancerIP: 192.168.8.1
