---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-ftl.conf
  namespace: dns
data:
  pihole-FTL.conf: |
    MAXDBDAYS=7
    LOGFILE=/var/log/pihole/pihole-FTL.log
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: whitelist.txt
  namespace: dns
data:
  whitelist.txt: |
    ichnaea.netflix.com
    nrdp.nccp.netflix.com
    collector-medium.lightstep.com
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: adlists.list
  namespace: dns
data:
  adlists.list: |
    https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
    https://mirror1.malwaredomains.com/files/justdomains
    http://sysctl.org/cameleon/hosts
    https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
    https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
    https://hosts-file.net/ad_servers.txt
    https://blocklist.site/app/dl/tracking
    https://blocklist.site/app/dl/malware
    https://blocklist.site/app/dl/spam
    https://blocklist.site/app/dl/ads
    https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV.txt
    https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/android-tracking.txt
    https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
    https://raw.githubusercontent.com/StevenBlack/hosts/master/data/add.2o7Net/hosts
    https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-blocklist.txt
    https://v.firebog.net/hosts/Easyprivacy.txt
    https://v.firebog.net/hosts/Prigent-Ads.txt
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom.list
  namespace: dns
data:
  custom.list: |
    192.168.0.10 dragonbase.lan
    192.168.0.20 dragonaphallway.lan
    192.168.8.2 dragondata.lan
    192.168.0.1 dragonfire.lan
    192.168.0.6 dragonprinter.lan
    192.168.0.50 amd64node1.lan
    192.168.0.51 amd64node2.lan
    192.168.0.52 amd64node3.lan
    192.168.0.53 amd64node4.lan
    192.168.0.54 amd64node5.lan
    192.168.0.60 arm64node1.lan
    192.168.8.20 hass.lan
