apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: minecraft
  name: minecraft
  labels:
    app: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      role: minecraft
  template:
    metadata:
      labels:
        role: minecraft
    spec:
      nodeSelector:
        kubernetes.io/hostname: "amd64node3"
      containers:
      - name: minecraft
        image: dragoncrafted87/alpine-minecraft:edge
        imagePullPolicy: Always
        ports:
        - name: minecraft
          containerPort: 25565
          protocol: TCP
        - name: rcon
          containerPort: 25575
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /mnt/minecraft
      volumes:
      - name: data
        nfs:
          server: 10.98.210.174
          path: /Minecraft-Fabric
