apiVersion: v1
kind: Service
metadata:
  namespace: minecraft
  name: minecraft
spec:
  ports:
    - name: minecraft
      port: 25565
      protocol: TCP
    - name: rcon
      port: 25575
      protocol: TCP
  selector:
    role: minecraft
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: minecraft
  name: minecraft
  labels:
    app: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      role: minecraft
  template:
    metadata:
      labels:
        role: minecraft
    spec:
      containers:
      - name: minecraft
        image: dragoncrafted87/alpine-spigot:edge
        imagePullPolicy: Always
        env:
        - name: SPIGOT_VERSION
          value: "1.16.1"
        - name: SPIGOT_SKIP_BACKUP
          value: "True"
        - name: SPIGOT_SKIP_BUILD
          value: "True"
        - name: RCON_PASSWORD
          value: "rcon"
        ports:
        - name: minecraft
          containerPort: 25565
          protocol: TCP
        - name: rcon
          containerPort: 25575
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /mnt/minecraft
      volumes:
      - name: data
        flexVolume:
          driver: "fstab/cifs"
          secretRef:
            name: cifs-secret
          options:
            networkPath: "//192.168.8.2/Persistent/Minecraft"
            mountOptions: "dir_mode=0777,file_mode=0777,noperm"
