apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calligraphy-backups
  namespace: storage
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: smb-static
  volumeName: calligraphy-backups
  resources:
    requests:
      storage: 1Ti
