kind: Service
apiVersion: v1
metadata:
  name: mqtt
  namespace: iot
spec:
  selector:
    role: mqtt
  ports:
  - name: mqtt
    port: 1883
    targetPort: 1883
    protocol: TCP
  type: LoadBalancer
  loadBalancerIP: 192.168.8.21
