apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: games
  name: playit-agent
  labels:
    app: playit-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      role: playit-agent
  template:
    metadata:
      labels:
        role: playit-agent
    spec:
      containers:
      - name: playit-agent
        image: dragoncrafted87/alpine-playit-agent:latest
        imagePullPolicy: Always
        env:
        - name: TZ
          value: America/Chicago
        volumeMounts:
        - name: config
          mountPath: /home/docker/playit.toml
          subPath: playit.toml
          readOnly: false
      volumes:
      - name: config
        nfs:
          server: 10.152.183.213
          path: /playit
