---
kind: Service
apiVersion: v1
metadata:
    name: home-assistant
    namespace: iot
spec:
    selector:
        role: home-assistant
    ports:
    - protocol: TCP
        port: 80
        name: ha-web
        targetPort: 8123
    type: LoadBalancer
    loadBalancerIP: 192.168.8.20
