apiVersion: v1
kind: Service
metadata:
  namespace: games
  name: foundry
  annotations:
    metallb.universe.tf/allow-shared-ip: foundry
spec:
  ports:
  - name: foundry
    protocol: TCP
    port: 80
    targetPort: 30000
  selector:
    role: foundry
  type: LoadBalancer
  loadBalancerIP: 192.168.8.40
