apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: games
  name: foundry
  labels:
    app: foundry
spec:
  replicas: 1
  selector:
    matchLabels:
      role: foundry
  template:
    metadata:
      labels:
        role: foundry
    spec:
      securityContext:
        fsGroup: 1000
      dnsConfig:
        options:
        - name: timeout
          value: '100'
        - name: attempts
          value: '5'
        - name: ndots
          value: '1'
      containers:
      - name: foundry
        image: ghcr.io/dragoncrafted87/alpine-foundry-vtt-runner:2.0.1
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: America/Chicago
        ports:
        - name: server
          containerPort: 30000
          protocol: TCP
        volumeMounts:
        - name: server
          mountPath: /home/docker/server
        - name: data
          mountPath: /home/docker/data
      volumes:
      - name: server
        nfs:
          server: castellan.stealthdragonland.net
          path: /srv/data/foundry/server
      - name: data
        nfs:
          server: castellan.stealthdragonland.net
          path: /srv/data/foundry/data
