apiVersion: v1
kind: Service
metadata:
    namespace: media
    name: plex-tcp
    annotations:
        metallb.universe.tf/allow-shared-ip: plex
spec:
    ports:
    -   name: server
        port: 32400
        protocol: TCP
    selector:
        role: plex
    type: LoadBalancer
    loadBalancerIP: 192.168.8.31
