apiVersion: batch/v1
kind: Job
metadata:
    name: mc-hardcore-backup-job
    namespace: storage
    labels:
        app: mc-hardcore-backup-job
spec:
    template:
        metadata:
            name: mc-hardcore-backup-job
        spec:
            containers:
            -   name: mc-hardcore-backup
                image: dragoncrafted87/alpine-backup-cron:edge
                imagePullPolicy: Always
                env:
                -   name: TZ
                    value: America/Chicago
                -   name: BACKUP_NAME
                    value: minecraft-uhc-backup
                volumeMounts:
                -   name: minecraft-uhc
                    mountPath: /mnt/source
                -   name: backup
                    mountPath: /mnt/backups
            restartPolicy: OnFailure
            volumes:
            -   name: minecraft-uhc
                nfs:
                    server: 10.152.183.213
                    path: /minecraft-hardcore
            -   name: backup
                flexVolume:
                    driver: fstab/cifs
                    secretRef:
                        name: cifs-secret
                    options:
                        networkPath: //192.168.8.2/Backups/K8s/
                        mountOptions: dir_mode=0755,file_mode=0644,noperm
