# yamllint disable rule:indentation
apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-configuration
  namespace: dns
data:
  Caddyfile: |
    stealthdragonland.net {
    }

    dragoncrafted87.dev {
    }

    foundry.stealthdragonland.net {
      reverse_proxy 192.168.8.40
    }

    media.stealthdragonland.net {
      reverse_proxy 192.168.8.30:80
    }

    time.stealthdragonland.net {
      reverse_proxy 192.168.8.50:80
    }

    weatherhub.stealthdragonland.net {
      reverse_proxy 192.168.0.102:80
    }
