apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dns
  name: caddy
  labels:
    app: caddy
spec:
  replicas: 1
  selector:
    matchLabels:
      role: caddy
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        role: caddy
    spec:
      nodeSelector:
        kubernetes.io/hostname: amd64node5.lan
      restartPolicy: Always
      containers:
      - name: caddy
        image: caddy:2.7.6-alpine
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: America/Chicago
        ports:
        - containerPort: 80
          name: http-tcp
          protocol: TCP
        - containerPort: 443
          name: https-tcp
          protocol: TCP
        - containerPort: 443
          name: https-udp
          protocol: UDP
        volumeMounts:
        - name: conf
          mountPath: /etc/caddy/Caddyfile
          subPath: Caddyfile
        - name: data
          mountPath: /data
        - name: config
          mountPath: /config
      volumes:
      - name: conf
        configMap:
          name: caddy-configuration
          items:
          - key: Caddyfile
            path: Caddyfile
      - name: data
        nfs:
          server: 192.168.0.51
          path: /srv/data/caddy/data
      - name: config
        nfs:
          server: 192.168.0.51
          path: /srv/data/caddy/config
