apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: iot
  name: weather
  labels:
    app.kubernetes.io/name: weather
spec:
  replicas: 1
  selector:
    matchLabels:
      role: weather
  template:
    metadata:
      labels:
        role: weather
    spec:
      containers:
      - name: weather
        image: ghcr.io/dragoncrafted87/alpine-ambient-weather-mqtt-publisher:2.0.1
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: America/Chicago
        - name: MQTT_SERVER
          value: 10.152.183.226
        - name: MQTT_SERVER_PORT
          value: '1883'
        ports:
        - containerPort: 80
          name: weather
          protocol: TCP
      restartPolicy: Always
