apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: infrastructure
  name: pomerium
  labels:
    app: pomerium
spec:
  replicas: 1
  selector:
    matchLabels:
      role: pomerium
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        role: pomerium
    spec:
      nodeSelector:
        kubernetes.io/hostname: amd64node5.lan
      restartPolicy: Always
      containers:
      - name: pomerium
        image: pomerium/pomerium:nonroot-v0.26.1
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: America/Chicago
        # livenessProbe:
        #   httpGet:
        #     path: /healthz
        #     port: 8081
        #   initialDelaySeconds: 15
        #   periodSeconds: 20
        # readinessProbe:
        #   httpGet:
        #     path: /readyz
        #     port: 8081
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        ports:
        - containerPort: 443
          name: https-tcp
          protocol: TCP
        - containerPort: 443
          name: https-udp
          protocol: UDP
        volumeMounts:
        - name: conf
          mountPath: /pomerium/config.yaml
          subPath: config.yaml
        - name: data
          mountPath: /data
        - name: config
          mountPath: /config
      volumes:
      - name: conf
        configMap:
          name: pomerium-configuration
          items:
          - key: config.yaml
            path: config.yaml
      - name: data
        nfs:
          server: castellan.stealthdragonland.net
          path: /srv/data/pomerium/data
      - name: config
        nfs:
          server: castellan.stealthdragonland.net
          path: /srv/data/pomerium/config
