apiVersion: v1
kind: Secret
metadata:
  name: cifs-secret
  namespace: default
type: fstab/cifs
data:
  username: 'c21idXNlcg==' # if using my image for samba/greyhole this is the smbuser in the container
  password: 'replace me with base64 encoded password'
