---
apiVersion: v1
kind: Pod
metadata:
  name: cifs-test
  namespace: storage
spec:
  containers:
  - name: busybox
    image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: test
      mountPath: /data
  volumes:
    - name: test
      flexVolume:
        driver: "fstab/cifs"
        secretRef:
          name: cifs-secret
        options:
          networkPath: "//192.168.8.2/Persistent/Test"
          mountOptions: "dir_mode=0755,file_mode=0644,noperm"
