apiVersion: v1
kind: Service
metadata:
  namespace: storage
  name: greyhole
spec:
  ports:
    - name: samba1
      port: 139
      protocol: TCP
    - name: samba2
      port: 445
      protocol: TCP
  selector:
    role: greyhole
  type: LoadBalancer
  loadBalancerIP: 192.168.8.2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: storage
  name: greyhole
  labels:
    app: greyhole
spec:
  replicas: 1
  selector:
    matchLabels:
      role: greyhole
  template:
    metadata:
      labels:
        role: greyhole
    spec:
      nodeSelector:
        kubernetes.io/hostname: "amd64node2"
      containers:
      - name: greyhole
        image: dragoncrafted87/alpine-greyhole:edge
        imagePullPolicy: Always
        securityContext:
          privileged: true
        ports:
        - containerPort: 139
          name: smb1
          protocol: TCP
        - containerPort: 445
          name: smb2
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: 139
          initialDelaySeconds: 60
          timeoutSeconds: 5
        volumeMounts:
        - name: greyhole-config
          mountPath: /mnt/config
        - name: greyhole-lz
          mountPath: /mnt/landing_zone
        - name: greyhole-enclosure1-drive1
          mountPath: /mnt/enclosure1_drive1
        - name: greyhole-enclosure1-drive2
          mountPath: /mnt/enclosure1_drive2
        - name: greyhole-enclosure1-drive3
          mountPath: /mnt/enclosure1_drive3
        - name: greyhole-enclosure1-drive4
          mountPath: /mnt/enclosure1_drive4

        - name: greyhole-enclosure2-drive1
          mountPath: /mnt/enclosure2_drive1
        - name: greyhole-enclosure2-drive2
          mountPath: /mnt/enclosure2_drive2
        - name: greyhole-enclosure2-drive3
          mountPath: /mnt/enclosure2_drive3
        - name: greyhole-enclosure2-drive4
          mountPath: /mnt/enclosure2_drive4
        - name: greyhole-enclosure2-drive5
          mountPath: /mnt/enclosure2_drive5
      volumes:
      - name: greyhole-config
        hostPath:
          path: /mnt/staging_area/config/
          type: ""
      - name: greyhole-lz
        hostPath:
          path: /mnt/staging_area/landing_zone/
          type: ""

      - name: greyhole-enclosure1-drive1
        hostPath:
          path: /mnt/enclosure1_drive1/
          type: ""
      - name: greyhole-enclosure1-drive2
        hostPath:
          path: /mnt/enclosure1_drive2/
          type: ""
      - name: greyhole-enclosure1-drive3
        hostPath:
          path: /mnt/enclosure1_drive3/
          type: ""
      - name: greyhole-enclosure1-drive4
        hostPath:
          path: /mnt/enclosure1_drive4/
          type: ""

      - name: greyhole-enclosure2-drive1
        hostPath:
          path: /mnt/enclosure2_drive1/
          type: ""
      - name: greyhole-enclosure2-drive2
        hostPath:
          path: /mnt/enclosure2_drive2/
          type: ""
      - name: greyhole-enclosure2-drive3
        hostPath:
          path: /mnt/enclosure2_drive3/
          type: ""
      - name: greyhole-enclosure2-drive4
        hostPath:
          path: /mnt/enclosure2_drive4/
          type: ""
      - name: greyhole-enclosure2-drive5
        hostPath:
          path: /mnt/enclosure2_drive5/
          type: ""
