---
kind: Service
apiVersion: v1
metadata:
  namespace: storage
  name: nfs-enclosure2-drive1
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    role: nfs-enclosure2-drive1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: storage
  name: nfs-enclosure2-drive1
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nfs-enclosure2-drive1
  template:
    metadata:
      labels:
        role: nfs-enclosure2-drive1
    spec:
      nodeSelector:
        kubernetes.io/hostname: "dragonmaster"
      containers:
      - name: nfs-dragonshadow
        image: gcr.io/google_containers/volume-nfs:0.8
        imagePullPolicy: Always
        ports:
        - containerPort: 2049
          name: nfs
          protocol: TCP
        - containerPort: 20048
          name: mountd
          protocol: TCP
        - containerPort: 111
          name: rpcbind
          protocol: TCP
        resources: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /exports
          name: nfs-export
      restartPolicy: Always
      volumes:
      - hostPath:
          path: /mnt/enclosure2_drive1
          type: ""
        name: nfs-export
