# yamllint disable rule:indentation
apiVersion: v1
kind: ConfigMap
metadata:
  name: greyhole.conf
  namespace: storage
data:
  greyhole.conf: |
    # This file is part of Greyhole.

    #### Database Connection ####
        db_engine = mysql
        db_host = 127.0.0.1
        db_user = greyhole_user
        db_pass = 89y63jdwe
        db_name = greyhole

    #### Timezone ####
        timezone = America/Chicago

    #### Greyhole Daemon Niceness ####
        daemon_niceness = 1

    #### Greyhole Log File ####
        greyhole_log_file = /mnt/config/log/greyhole.log
        greyhole_error_log_file = /mnt/config/log/greyhole.err
        log_level = DEBUG
        log_memory_usage = no
        check_for_open_files = yes

    #### Copying ####
        calculate_md5 = yes
        parallel_copying = yes

    #### Shares Settings ####
        num_copies[Backups] = 2
        num_copies[Storage] = 3
        num_copies[Unrestricted] = 2

    #### Storage Pool ####
        storage_pool_drive = /mnt/enclosure1_drive1, min_free: 100gb
        storage_pool_drive = /mnt/enclosure1_drive2, min_free: 100gb
        storage_pool_drive = /mnt/enclosure1_drive3, min_free: 100gb
        storage_pool_drive = /mnt/enclosure1_drive4, min_free: 100gb
        storage_pool_drive = /mnt/enclosure1_drive5, min_free: 100gb
        storage_pool_drive = /mnt/enclosure1_drive6, min_free: 100gb
        storage_pool_drive = /mnt/enclosure1_drive7, min_free: 100gb
        storage_pool_drive = /mnt/enclosure1_drive8, min_free: 1000gb

        drive_selection_algorithm = least_used_space

    #### Sticky Files ####
        df_cache_time = 120

    #### Trash ####
        delete_moves_to_trash = yes
        modified_moves_to_trash = no

    #### Memory Limit ###
        memory_limit = 2G

    #### Ignored files & folders ####
        # rsync temporary files
        ignored_files = \..*\.[0-9a-zA-Z]{6}
        # Microsoft Office temporary files
        ignored_files = [0-9A-F]{8}\.tmp
        # CrashPlan (restore) temporary files
        ignored_files = \.cprestoretmp.*
        # SABnzbd temporary folders when extracting a download
        ignored_folders = .*/_UNPACK_.*
        # NZBget temporary folders when extracting a download
        ignored_folders = .*/_unpack.*
        # Plex Optimized Versions temporary files
        ignored_folders = .*/inProgress/.*
        # Mac metadata files
        ignored_files = \.DS_Store
        # Windows thumbs database files
        ignored_files = Thumb.db
        ignored_files = desktop.ini
